# Minimal Jekyll Portfolio Configuration

# Basic Site Settings
locale: "en-US"
title: "Liron's Portfolio"
description: "Showcasing projects in Electrical and Computer Engineering"
url: "https://your-portfolio-url.com" # Update with your live site URL
baseurl: "" # No subpath for portfolio site
repository: "LironL99/portfolio"

# Logo
logo: "assets/img/rsz_2profile_pic_rnd.png"

# Author Information
author:
  name: "Liron"
  bio: "Student of Electrical and Computer Engineering specializing in VLSI and Computers tracks"
  email: "liron@example.com" # Update with your email
  github: "LironL99"

# Site Settings
teaser: "default-image.png" # Fallback image for teasers
future: true
comments: 
  provider: false # Disable comments for a portfolio site

# SEO Related
google_site_verification: "" 
bing_site_verification: ""
alexa_site_verification: ""
yandex_site_verification: ""

# Analytics
analytics:
  provider: "false" # No analytics for a personal portfolio

# Markdown Processing
markdown: kramdown

# Outputting
permalink: /:title/
timezone: Etc/UTC

# Plugins (keep minimal)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults for Pages and Projects
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      author_profile: false
