# Welcome to Liron's Portfolio!

# Basic Site Settings
locale                   : "en-US"
title                    : "Liron's Portfolio"
title_separator          : "-"
name                     : &name "Liron"
description              : &description "Portfolio of Liron, an Electrical and Computer Engineering student specializing in VLSI and Computers."
url                      : https://your-portfolio-url.github.io # Update with your actual URL
baseurl                  : "" # The subpath of your site, e.g. "/portfolio"
repository               : "LironL99/portfolio" # Update with your GitHub repository name

# Site Author
author:
  avatar           : "/assets/img/rsz_2profile_pic_rnd.png" # Path to your logo
  name             : "Liron"
  bio              : "Electrical and Computer Engineering student specializing in VLSI and Computers."
  location         : "Earth"
  email            : "your_email@example.com" # Update with your email

# Publication Category
publication_category:
  projects:
    title: 'Featured Projects'

# Site Settings
teaser                   : "default-teaser.png" # Replace with your teaser image filename
comments:
  provider               : false # Disable comments for portfolio
read_more                : "disabled" # Disable "Read more" links

# SEO Related
google_site_verification : # Insert your Google verification code if needed
bing_site_verification   : 
alexa_site_verification  : 
yandex_site_verification : 

# Analytics
analytics:
  provider               : "false" # Disable analytics for the portfolio

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .git
  - README.md
  - LICENSE

# Markdown Processing
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# HTML Compression
compress_html:
  clippings: all
