title: Liron's Portfolio
logo: /assets/img/20240616_191745.jpg
#description: A showcase of my projects in Electrical and Computer Engineering, focusing on VLSI and Computers.
#show_downloads: true
theme: jekyll-theme-minimal
