title: Liron Leibovich
logo: /assets/img/rsz_rsz_2profile_pic_rnd.png
theme: jekyll-theme-minimal  # Change this to any supported theme
google_analytics: "G-6924S3V27R"  # Your tracking ID
sass:
  style: compressed
