title: Liron's Portfolio
#logo: add logo
#description: A showcase of my projects in Electrical and Computer Engineering, focusing on VLSI and Computers.
#show_downloads: true
theme: jekyll-theme-minimal
